default: 
	gcc -Wall -Wextra -o simpsh simpsh.c -g


dist: 
	tar -czvf lab1-804769644.tar.gz Makefile README simpsh.c

clean: 
	rm -f simpsh

check:
	echo "To run test cases, please use command ./lab1a_sanity_script.sh 804769644"
	echo "This will run TA Bu's test cases. This is how I checked my program."


