#NAME: Mehar Nallamalli, Aditi Mittal
#EMAIL: mnallamalli97.ucla.edu, aditi.mittal2@gmail.com
#ID: 804769644, 104736807
#SLIPDAYS: 1

default: 
	rm -f lab3b
	echo '#!/usr/bin/python' > lab3b
	cat lab3b.py >> lab3b
	chmod a+x lab3b

dist: 
	tar -czvf lab3b-804769644.tar.gz Makefile README lab3b.py

clean: 
	rm -f lab3a lab3b-804769644.tar.gz lab3b


