#NAME: Mehar Nallamalli, Aditi Mittal
#EMAIL: mnallamalli97.ucla.edu,  aditi.mittal2@gmail.com
#ID: 804769644, 104736807
#SLIPDAYS: 1

default: 
	gcc -Wall -Wextra -o lab3a lab3a.c -g -w -std=c99


dist: 
	tar -czvf lab3a-804769644.tar.gz Makefile README lab3a.c ext2_fs.h

clean: 
	rm -f lab3a lab3a-804769644.tar.gz *_.csv


